### ISSUE TITLE
Yeoman crashes after install.

### ISSUE THREAD

**Issue by faddiv** [MattJeanes/AngularBasic#1]
Hy After installed this generator the yeoman crashes with the following error:
PS D:\Projects\_Egyeb\YoCore> yo

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

d:\temp\npm-modules\node_modules\yo\node_modules\update-notifier\index.js:30
                        throw new Error('pkg.name and pkg.version required');
                        ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (d:\temp\npm-modules\node_modules\yo\node_modules\update-notifier\index.js:30:10)
    at module.exports.options (d:\temp\npm-modules\node_modules\yo\node_modules\update-notifier\index.js:145:25)
    at resolveGenerators (d:\temp\npm-modules\node_modules\yo\lib\router.js:74:20)
    at d:\temp\npm-modules\node_modules\yo\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (d:\temp\npm-modules\node_modules\yo\node_modules\lodash\lodash.js:3001:24)
    at d:\temp\npm-modules\node_modules\yo\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (d:\temp\npm-modules\node_modules\yo\node_modules\lodash\lodash.js:9359:14)
    at Router.updateAvailableGenerators (d:\temp\npm-modules\node_modules\yo\lib\router.js:83:7)
    at runYo (d:\temp\npm-modules\node_modules\yo\lib\cli.js:174:10)
    at env.lookup (d:\temp\npm-modules\node_modules\yo\lib\cli.js:134:7)

**Comment by AmyJeanes** [comment]
Hi, thanks for raising this issue. Do you have a list of commands I could enter to reproduce this issue? Thanks

**Comment by faddiv** [comment]
I installed the generator with
npm install -g generator-angular-basic
Then I tried to start yeoman:
yo

I think the problem simply is that there is no definition file for this package. Check this tutorial:
http://yeoman.io/authoring/

**Comment by AmyJeanes** [comment]
Thanks, got it - should be ok now as of 2.0.0. Keep in mind that I've upgraded it to webpack now, but the old systemjs version is still available on 1.x and the systemjs branches
